#! /bin/sh
### BEGIN INIT INFO
# Provides: vpnclient
# Required-Start: $all
# Required-Stop: $network $local_fs $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start VPN Client at boot time
# chkconfig: 345 44 56
# description: Start VPN Client at boot time.
# processname: vpnclient
### END INIT INFO
 
# /etc/init.d/vpnclient
 
case "$1" in
    start)
        echo "Starting VPN Client"
        /usr/local/bin/vpnclient start
        sleep 1
        ifdown vpn_vpn
        sleep 1
        ifup vpn_vpn
        sleep 1
        route add -host 55.55.55.55 gw 192.168.0.1
        route del default
        route add default gw 192.168.10.1 dev vpn_vpn
        ;;
 
    stop)
        echo "Stopping VPN Client"
        /usr/local/bin/vpnclient stop
        route del -host 55.55.55.55
        route del default
        route add default gw 192.168.0.1 dev eth0
        ;;
 
    *)
        echo "Usage: /etc/init.d/vpnclient {start|stop}"
        exit 1
        ;;
esac
 
exit 0
